### ISSUE TITLE
Not Able To Get The App

### ISSUE THREAD

**Issue by phablousGh** [aerele/pwa-builder#6]
Hi please i get this error when i'm trying to get the app. I'm using frappe develop branch. Please help:

frappe@me-Latitude-5480:~/vue_office$ bench get-app https://github.com/aerele/pwa-builder.git
Getting pwa-builder
$ git clone https://github.com/aerele/pwa-builder.git  --depth 1 --origin upstream
Cloning into 'pwa-builder'...
remote: Enumerating objects: 193, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 193 (delta 16), reused 141 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (193/193), 9.52 MiB | 1.67 MiB/s, done.
Resolving deltas: 100% (16/16), done.
ERROR: Invalid value (at line 12, column 5)
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 235, in install
    app_name = get_app_name(self.bench.name, self.app_name)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/app.py", line 244, in get_app_name
    app_name = load(f).get("project", {}).get("name")
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 616, in parse_value
    return parse_array(src, pos, parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 420, in parse_array
    pos, val = parse_value(src, pos, parse_float)
  File "/usr/local/lib/python3.10/dist-packages/tomli/_parser.py", line 649, in parse_value
    raise suffixed_err(src, pos, "Invalid value")
tomli.TOMLDecodeError: Invalid value (at line 12, column 5)
![Screenshot from 2024-10-04 15-23-10](https://github.com/user-attachments/assets/0a63e077-cce3-4b63-b597-411e5c5e0d07)

**Comment by hmb47** [comment]
the same issue

**Comment by Altrix-One** [comment]
I fixed the issue by rectifying the syntax error in the pyproject.toml file. Just fix line 12 or comment out the dependency with a #

**Comment by nilpatel42** [comment]
same issue and also not able to install, needs proper installation steps

**Comment by Altrix-One** [comment]
> same issue and also not able to install, needs proper installation steps
> 
> 

Fix the issue mentioned in my comment earlier. 

- Bench get-app pwa-builder (or git link)
- Bench --site (site name) install-app pwa-builder

Install systemctl and then run Bench Stop and Bench Start together.

**Comment by nilpatel42** [comment]
I tried with main branch, in which that not exists and, 

but during installation it gives error and site go into internal server eror

"(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
warning ../../../../package.json: No license field
$ cp ../pwa_builder/public/frontend/index.html ../pwa_builder/www/frontend.html
cp: cannot create regular file '../pwa_builder/www/frontend.html': No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/cerp/frappe-bench/apps/frappe/esbuild/esbuild.js:448:5)
    at execute (/home/cerp/frappe-bench/apps/frappe/esbuild/esbuild.js:125:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1694602,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cerp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/cerp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cerp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/cerp/frappe-bench/apps/frappe/frappe/commands/utils.py", line 77, in build
    bundle(
  File "/home/cerp/frappe-bench/apps/frappe/frappe/build.py", line 254, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/cerp/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run build --apps pwa_builder --run-build-command' returned non-zero exit status 1.
ERROR: bench build --app pwa_builder
subprocess.CalledProcessError: Command 'bench build --app pwa_builder' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cerp/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/app.py", line 777, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/app.py", line 254, in install
    install_app(
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/app.py", line 925, in install_app
    build_assets(bench_path=bench_path, app=app, using_cached=using_cached)
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 380, in build_assets
    exec_cmd(command, cwd=bench_path, env=env)
  File "/home/cerp/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 178, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app pwa_builder

"

and without forking the branch can we follow this step 

> "I fixed the issue by rectifying the syntax error in the pyproject.toml file. Just fix line 12 or comment out the dependency with a #"

**Comment by phablousGh** [comment]
When i try to export this is what i get. I am doing it on my local machine.
![Screenshot from 2024-10-14 16-47-13](https://github.com/user-attachments/assets/73414345-cd3a-4d49-8203-9b403dee306c)
![Screenshot from 2024-10-14 16-46-54](https://github.com/user-attachments/assets/3f9800c1-3e86-4083-9622-5e8eb98fab27)
